In [4]:
import pandas as pd

df = pd.read_csv("../raw/news_raw.csv")
df.head()

,source_name,author,title,description,url,keyword,language,published_date,collected_at
0,GNews,NaN,Why the Indo-Pacific needs to be central to In...,Why the Indo-Pacific needs to be central to In...,https://news.google.com/rss/articles/CBMilgFBV...,"indo, pacific, needs",en,2026-07-17 03:46:42,2026-07-17 03:46:42
1,GNews,NaN,"Beyond political reshuffles, renew education i...","Beyond political reshuffles, renew education i...",https://news.google.com/rss/articles/CBMirwFBV...,"beyond, political, reshuffles",en,2026-07-17 03:46:42,2026-07-17 03:46:42
2,GNews,NaN,India vs England: Doors closing down fast on R...,India vs England: Doors closing down fast on R...,https://news.google.com/rss/articles/CBMiwAFBV...,"india, england, doors",en,2026-07-17 03:46:42,2026-07-17 03:46:42
3,GNews,NaN,Is OnePlus exiting India? Explained - The Hindu,Is OnePlus exiting India? Explained The Hindu,https://news.google.com/rss/articles/CBMioAFBV...,"oneplus, exiting, india",en,2026-07-17 03:46:42,2026-07-17 03:46:42
4,GNews,NaN,"India to face Malaysia, Syria, Iraq in AFC U17...","India to face Malaysia, Syria, Iraq in AFC U17...",https://news.google.com/rss/articles/CBMirwFBV...,"india, face, malaysia",en,2026-07-17 03:46:42,2026-07-17 03:46:42

In [5]:
df.head()

,source_name,author,title,description,url,keyword,language,published_date,collected_at
0,GNews,NaN,Why the Indo-Pacific needs to be central to In...,Why the Indo-Pacific needs to be central to In...,https://news.google.com/rss/articles/CBMilgFBV...,"indo, pacific, needs",en,2026-07-17 03:46:42,2026-07-17 03:46:42
1,GNews,NaN,"Beyond political reshuffles, renew education i...","Beyond political reshuffles, renew education i...",https://news.google.com/rss/articles/CBMirwFBV...,"beyond, political, reshuffles",en,2026-07-17 03:46:42,2026-07-17 03:46:42
2,GNews,NaN,India vs England: Doors closing down fast on R...,India vs England: Doors closing down fast on R...,https://news.google.com/rss/articles/CBMiwAFBV...,"india, england, doors",en,2026-07-17 03:46:42,2026-07-17 03:46:42
3,GNews,NaN,Is OnePlus exiting India? Explained - The Hindu,Is OnePlus exiting India? Explained The Hindu,https://news.google.com/rss/articles/CBMioAFBV...,"oneplus, exiting, india",en,2026-07-17 03:46:42,2026-07-17 03:46:42
4,GNews,NaN,"India to face Malaysia, Syria, Iraq in AFC U17...","India to face Malaysia, Syria, Iraq in AFC U17...",https://news.google.com/rss/articles/CBMirwFBV...,"india, face, malaysia",en,2026-07-17 03:46:42,2026-07-17 03:46:42

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 509 entries, 0 to 508
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   source_name     509 non-null    object
 1   author          99 non-null     object
 2   title           509 non-null    object
 3   description     509 non-null    object
 4   url             509 non-null    object
 5   keyword         509 non-null    object
 6   language        509 non-null    object
 7   published_date  509 non-null    object
 8   collected_at    509 non-null    object
dtypes: object(9)
memory usage: 35.9+ KB

In [7]:
df.describe(include="all")

,source_name,author,title,description,url,keyword,language,published_date,collected_at
count,509,99,509,509,509,509,509,509,509
unique,5,39,507,509,509,504,3,387,11
top,Hindustan Times,TOI WORLD DESK,Rejuvenated India aim to seal series - Cricbuzz,Why the Indo-Pacific needs to be central to In...,https://news.google.com/rss/articles/CBMilgFBV...,"india, trade, deal",en,2026-07-17 03:46:42,2026-07-16 03:47:05
freq,164,17,2,1,1,3,507,49,110

In [8]:
df.shape

(509, 9)

In [9]:
df.isnull().sum()

source_name         0
author            410
title               0
description         0
url                 0
keyword             0
language            0
published_date      0
collected_at        0
dtype: int64

In [10]:
df["author"] = df["author"].fillna("Unknown")

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df = df.drop_duplicates(subset=["title"])

In [13]:
import re

def clean_text(text):
    text = str(text)
    text = text.lower()
    text = re.sub(r"http\S+", "", text)
    text = re.sub(r"[^a-zA-Z0-9 ]", "", text)
    text = text.strip()
    return text

df["title"] = df["title"].apply(clean_text)

In [14]:
df.head(5)

,source_name,author,title,description,url,keyword,language,published_date,collected_at
0,GNews,Unknown,why the indopacific needs to be central to ind...,Why the Indo-Pacific needs to be central to In...,https://news.google.com/rss/articles/CBMilgFBV...,"indo, pacific, needs",en,2026-07-17 03:46:42,2026-07-17 03:46:42
1,GNews,Unknown,beyond political reshuffles renew education in...,"Beyond political reshuffles, renew education i...",https://news.google.com/rss/articles/CBMirwFBV...,"beyond, political, reshuffles",en,2026-07-17 03:46:42,2026-07-17 03:46:42
2,GNews,Unknown,india vs england doors closing down fast on ro...,India vs England: Doors closing down fast on R...,https://news.google.com/rss/articles/CBMiwAFBV...,"india, england, doors",en,2026-07-17 03:46:42,2026-07-17 03:46:42
3,GNews,Unknown,is oneplus exiting india explained the hindu,Is OnePlus exiting India? Explained The Hindu,https://news.google.com/rss/articles/CBMioAFBV...,"oneplus, exiting, india",en,2026-07-17 03:46:42,2026-07-17 03:46:42
4,GNews,Unknown,india to face malaysia syria iraq in afc u17 w...,"India to face Malaysia, Syria, Iraq in AFC U17...",https://news.google.com/rss/articles/CBMirwFBV...,"india, face, malaysia",en,2026-07-17 03:46:42,2026-07-17 03:46:42

In [15]:
df["description"] = df["description"].apply(clean_text)

In [16]:
df["published_date"] = pd.to_datetime(df["published_date"])

In [17]:
df["year"] = df["published_date"].dt.year
df["month"] = df["published_date"].dt.month
df["day"] = df["published_date"].dt.day
df["weekday"] = df["published_date"].dt.day_name()

In [18]:
df = df[df["url"].str.startswith("http", na=False)]

In [19]:
df = df[df["title"].str.len() > 5]

In [20]:
df["language"] = df["language"].str.lower()

In [21]:
df.info()

df.isnull().sum()

df.shape

<class 'pandas.core.frame.DataFrame'>
Index: 507 entries, 0 to 508
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   source_name     507 non-null    object
 1   author          507 non-null    object
 2   title           507 non-null    object
 3   description     507 non-null    object
 4   url             507 non-null    object
 5   keyword         507 non-null    object
 6   language        507 non-null    object
 7   published_date  507 non-null    datetime64[ns]
 8   collected_at    507 non-null    object
 9   year            507 non-null    int32
 10  month           507 non-null    int32
 11  day             507 non-null    int32
 12  weekday         507 non-null    object
dtypes: datetime64[ns](1), int32(3), object(9)
memory usage: 49.5+ KB

(507, 13)

In [22]:
df["collected_at"] = pd.to_datetime(df["collected_at"])

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 507 entries, 0 to 508
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   source_name     507 non-null    object
 1   author          507 non-null    object
 2   title           507 non-null    object
 3   description     507 non-null    object
 4   url             507 non-null    object
 5   keyword         507 non-null    object
 6   language        507 non-null    object
 7   published_date  507 non-null    datetime64[ns]
 8   collected_at    507 non-null    datetime64[ns]
 9   year            507 non-null    int32
 10  month           507 non-null    int32
 11  day             507 non-null    int32
 12  weekday         507 non-null    object
dtypes: datetime64[ns](2), int32(3), object(8)
memory usage: 49.5+ KB

In [24]:
df.duplicated().sum()

np.int64(0)

In [25]:
df["title"].duplicated().sum()

np.int64(0)

In [26]:
df["url"].duplicated().sum()

np.int64(0)

In [27]:
(df == "").sum()

source_name       0
author            0
title             0
description       0
url               0
keyword           0
language          0
published_date    0
collected_at      0
year              0
month             0
day               0
weekday           0
dtype: int64

In [28]:
(df.apply(lambda col: col.astype(str).str.strip() == "")).sum()

source_name       0
author            0
title             0
description       0
url               0
keyword           0
language          0
published_date    0
collected_at      0
year              0
month             0
day               0
weekday           0
dtype: int64

In [29]:
df["language"].value_counts()

language
en    505
fr      1
nl      1
Name: count, dtype: int64

In [30]:
df[df["language"] != "en"]

,source_name,author,title,description,url,keyword,language,published_date,collected_at,year,month,day,weekday
223,GNews,Unknown,india raises taxes on diesel and jet fuel expo...,india raises taxes on diesel and jet fuel expo...,https://news.google.com/rss/articles/CBMimgFBV...,"india, raises, taxes",fr,2026-07-16 03:47:14,2026-07-16 03:47:14,2026,7,16,Thursday
508,India Today,Unknown,delhi doesnt get rain it gets ambushed,delhi doesnt get rain it gets ambushed,https://www.indiatoday.in/diu/story/delhi-rain...,"delhi, rain, gets",nl,2026-07-09 14:20:17,2026-07-16 03:47:06,2026,7,9,Thursday

In [31]:
df.loc[df["language"] == "fr", "language"] = "en"
df.loc[df["language"] == "nl", "language"] = "en"

In [32]:
df["language"].value_counts()

language
en    507
Name: count, dtype: int64

In [33]:
df["source_name"].value_counts()

source_name
Hindustan Times    164
GNews              119
Times of India      98
India Today         90
NDTV                36
Name: count, dtype: int64

In [34]:
print(df["published_date"].min())
print(df["published_date"].max())

2026-07-09 14:20:17
2026-07-17 03:46:42

In [35]:
df["title_length"] = df["title"].str.len()
df["description_length"] = df["description"].str.len()

In [36]:
df["url"].duplicated().sum()

np.int64(0)

In [37]:
df["title"].duplicated().sum()

np.int64(0)

In [38]:
(df == "").sum()

source_name           0
author                0
title                 0
description           0
url                   0
keyword               0
language              0
published_date        0
collected_at          0
year                  0
month                 0
day                   0
weekday               0
title_length          0
description_length    0
dtype: int64

In [39]:
(df.apply(lambda col: col.astype(str).str.strip() == "")).sum()

source_name           0
author                0
title                 0
description           0
url                   0
keyword               0
language              0
published_date        0
collected_at          0
year                  0
month                 0
day                   0
weekday               0
title_length          0
description_length    0
dtype: int64

In [40]:
df["author"].value_counts().head(10)

author
Unknown               409
TOI WORLD DESK         17
TOI SPORTS DESK        11
TOI TECH DESK           9
TOI BUSINESS DESK       8
TOI NEWS DESK           5
TNN                     5
BARSHA DUTTA            4
GLOBAL SPORTS DESK      3
SURENDRA SINGH          3
Name: count, dtype: int64

In [41]:
df[["title_length", "description_length"]].describe()

       title_length  description_length
count    507.000000          507.000000
mean      77.579882          165.530572
std       19.331900          123.128779
min       29.000000           38.000000
25%       67.000000           78.000000
50%       76.000000          112.000000
75%       86.000000          198.000000
max      265.000000          457.000000

In [42]:
df["url"].str.startswith("http").value_counts()

url
True    507
Name: count, dtype: int64

In [43]:
df["url"].duplicated().sum()

np.int64(0)

In [44]:
df["title"].duplicated().sum()

np.int64(0)

In [45]:
df["title"].duplicated().sum()

np.int64(0)

In [46]:
df.duplicated().sum()

np.int64(0)

In [47]:
df["url"].duplicated().sum()

np.int64(0)

In [48]:
df.isnull().sum()

source_name           0
author                0
title                 0
description           0
url                   0
keyword               0
language              0
published_date        0
collected_at          0
year                  0
month                 0
day                   0
weekday               0
title_length          0
description_length    0
dtype: int64

In [49]:
print("========== DATA QUALITY REPORT ==========")
print(f"Total Records: {len(df)}")
print(f"Duplicate URLs: {df['url'].duplicated().sum()}")
print(f"Duplicate Titles: {df['title'].duplicated().sum()}")
print(f"Missing Values:\n{df.isnull().sum()}")
print(f"Languages:\n{df['language'].value_counts()}")
print("=========================================")

========== DATA QUALITY REPORT ==========
Total Records: 507
Duplicate URLs: 0
Duplicate Titles: 0
Missing Values:
source_name           0
author                0
title                 0
description           0
url                   0
keyword               0
language              0
published_date        0
collected_at          0
year                  0
month                 0
day                   0
weekday               0
title_length          0
description_length    0
dtype: int64
Languages:
language
en    507
Name: count, dtype: int64
=========================================

In [50]:
df.to_csv("../cleaned/news_clean.csv", index=False)

In [52]:
df.head(508)

,source_name,author,title,description,url,keyword,language,published_date,collected_at,year,month,day,weekday,title_length,description_length
0,GNews,Unknown,why the indopacific needs to be central to ind...,why the indopacific needs to be central to ind...,https://news.google.com/rss/articles/CBMilgFBV...,"indo, pacific, needs",en,2026-07-17 03:46:42,2026-07-17 03:46:42,2026,7,17,Friday,83,83
1,GNews,Unknown,beyond political reshuffles renew education in...,beyond political reshuffles renew education in...,https://news.google.com/rss/articles/CBMirwFBV...,"beyond, political, reshuffles",en,2026-07-17 03:46:42,2026-07-17 03:46:42,2026,7,17,Friday,63,63
2,GNews,Unknown,india vs england doors closing down fast on ro...,india vs england doors closing down fast on ro...,https://news.google.com/rss/articles/CBMiwAFBV...,"india, england, doors",en,2026-07-17 03:46:42,2026-07-17 03:46:42,2026,7,17,Friday,88,88
3,GNews,Unknown,is oneplus exiting india explained the hindu,is oneplus exiting india explained the hindu,https://news.google.com/rss/articles/CBMioAFBV...,"oneplus, exiting, india",en,2026-07-17 03:46:42,2026-07-17 03:46:42,2026,7,17,Friday,45,45
4,GNews,Unknown,india to face malaysia syria iraq in afc u17 w...,india to face malaysia syria iraq in afc u17 w...,https://news.google.com/rss/articles/CBMirwFBV...,"india, face, malaysia",en,2026-07-17 03:46:42,2026-07-17 03:46:42,2026,7,17,Friday,108,108
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
504,Times of India,BARSHA DUTTA,erling haaland stunned fans when he mentioned ...,erling haalands old five girlfriends comment h...,https://timesofindia.indiatimes.com/sports/int...,"five, erling, haaland",en,2026-07-13 00:32:00,2026-07-15 17:54:19,2026,7,13,Monday,81,457
505,Times of India,TOI TECH DESK,jeff bezos exwife mackenzie scott donates to u...,mackenzie scott has donated twenty million dol...,https://timesofindia.indiatimes.com/technology...,"youth, mental, health",en,2026-07-12 07:37:14,2026-07-16 03:47:05,2026,7,12,Sunday,77,350
506,India Today,Unknown,sex consent 1st india today consent survey,sex consent st india today consent survey,https://www.indiatoday.in/magazine/cover-story...,"consent, india, today",en,2026-07-10 13:59:21,2026-07-17 03:46:33,2026,7,10,Friday,44,43
507,India Today,Unknown,why india needs a consent charter now guest c...,why india needs a consent charter now guest c...,https://www.indiatoday.in/magazine/india-today...,"india, needs, consent",en,2026-07-10 13:56:50,2026-07-17 03:46:33,2026,7,10,Friday,74,74
508,India Today,Unknown,delhi doesnt get rain it gets ambushed,delhi doesnt get rain it gets ambushed,https://www.indiatoday.in/diu/story/delhi-rain...,"delhi, rain, gets",en,2026-07-09 14:20:17,2026-07-16 03:47:06,2026,7,9,Thursday,38,38