In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
import warnings

warnings.filterwarnings('ignore')
print(f"all lib loaded")

all lib loaded

# Data understanding

In [2]:
df = pd.read_csv(r"C:\Users\Acer\OneDrive\Desktop\India-Trend-Radar\data\raw\youtube_20260701_20260731.csv")
df.head()

,video_id,title,channel_name,published_at,views,likes,comments,tags,keywords,video_url,collection_date,channel
0,KfT7AtKWS-A,GTA 5 LIVE | Train vs 100 Luxury Cars 😱🔥 कौन ब...,Sunil Gaming,2026-07-09T07:16:37Z,212532,1979,0,"gta 5 live, gta v train vs cars, gta 5 experim...","gta, live, train, 100, luxury, cars",https://www.youtube.com/watch?v=KfT7AtKWS-A,09/07/2026,NaN
1,Bp5Cq7PxQio,GTA 5 MOD LIVE | FULL TIMEPASS #gta #gtav #gaming,Gaming Anup Live,2026-07-09T07:16:08Z,432956,7631,0,"Gaming Anup, Gaming Anup shorts, Free fire, Ga...","gta, mod, live, timepass, gtav, gaming",https://www.youtube.com/watch?v=Bp5Cq7PxQio,09/07/2026,NaN
2,rwoT_ky5bnk,"09 जुलाई का मौसम| today weather update, heat w...",UMB NEWS,2026-07-09T07:03:02Z,118690,553,0,"mausam, mausam ki jankari, skymet weather fore...","today, weather, update, heat, wave, mausam, ja...",https://www.youtube.com/watch?v=rwoT_ky5bnk,09/07/2026,NaN
3,CWsACCb4vFg,GRANNY -1 LIVE 😉😱| GRANNY GAMEPLAY | #shorts #...,BOBIislive,2026-07-09T07:01:27Z,348481,8304,0,No Tags,"granny, live, gameplay, shorts, shortsfeed, sh...",https://www.youtube.com/watch?v=CWsACCb4vFg,09/07/2026,NaN
4,Zy8KDEJU3iY,"Bhai Tera Star Hai| Official Trailer| Raghav, ...",Eastwood Pictures Official,2026-07-09T06:00:06Z,16725,4990,198,#bhaiterastarhai,"bhai, tera, star, hai, raghav, niharika, vikal...",https://www.youtube.com/watch?v=Zy8KDEJU3iY,09/07/2026,NaN

In [3]:
print(f"Rows and Columns:{df.shape}")
print(f"columns name : {df.columns}")

Rows and Columns:(989, 12)
columns name : Index(['video_id', 'title', 'channel_name', 'published_at', 'views', 'likes',
       'comments', 'tags', 'keywords', 'video_url', 'collection_date',
       'channel'],
      dtype='object')

# Data profiling

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 989 entries, 0 to 988
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   video_id         989 non-null    object
 1   title            989 non-null    object
 2   channel_name     989 non-null    object
 3   published_at     989 non-null    object
 4   views            989 non-null    int64
 5   likes            989 non-null    int64
 6   comments         989 non-null    int64
 7   tags             989 non-null    object
 8   keywords         984 non-null    object
 9   video_url        989 non-null    object
 10  collection_date  989 non-null    object
 11  channel          0 non-null      float64
dtypes: float64(1), int64(3), object(8)
memory usage: 92.8+ KB

In [5]:
df.describe(include="all")

,video_id,title,channel_name,published_at,views,likes,comments,tags,keywords,video_url,collection_date,channel
count,989,989,989,989,9.890000e+02,989.000000,989.000000,989,984,989,989,0.0
unique,757,704,530,755,NaN,NaN,NaN,536,679,760,5,NaN
top,#NAME?,🔴 GTA 5 LIVE – DON’T BLINK! SECRET MOD ACTIVAT...,LoLzZz Gaming,2026-07-04T01:40:27Z,NaN,NaN,NaN,No Tags,"gta, live, gta5, gtav, gaming",https://www.youtube.com/watch?v=aPK_H9ZN0Ak,09/07/2026,NaN
freq,5,5,5,4,NaN,NaN,NaN,182,8,4,199,NaN
mean,NaN,NaN,NaN,NaN,6.772642e+05,16959.965622,1150.371082,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,1.827948e+06,52570.988262,5316.214031,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,6.021000e+03,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,8.363000e+04,891.000000,9.000000,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,2.105860e+05,2989.000000,71.000000,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,5.081160e+05,11004.000000,551.000000,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,2.529529e+07,640344.000000,127006.000000,NaN,NaN,NaN,NaN,NaN

In [6]:
# observations 
# dataset 989 rows and 12 col 
# numeric col include views , likes , comments 
# text col include title, channel_name,tags, keywords 

# published_at and collection_date require datatype validation 
# channel appears to contain missing values

# Data Quality Assessment

In [7]:
print("=" * 50)

print("Missing values report")

print("=" * 50)

missing_count = df.isnull().sum()
missing_per = round((df.isnull().sum() / len(df)) * 100,2)

missing_report = pd.DataFrame({
    "Missing values" : missing_count,
    "Percentge" : missing_per
})

print(missing_report)

==================================================
Missing values report
==================================================
                 Missing values  Percentge
video_id                      0       0.00
title                         0       0.00
channel_name                  0       0.00
published_at                  0       0.00
views                         0       0.00
likes                         0       0.00
comments                      0       0.00
tags                          0       0.00
keywords                      5       0.51
video_url                     0       0.00
collection_date               0       0.00
channel                     989     100.00

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.dtypes

video_id            object
title               object
channel_name        object
published_at        object
views                int64
likes                int64
comments             int64
tags                object
keywords            object
video_url           object
collection_date     object
channel            float64
dtype: object

In [10]:
df.nunique()

video_id           757
title              704
channel_name       530
published_at       755
views              989
likes              935
comments           496
tags               536
keywords           679
video_url          760
collection_date      5
channel              0
dtype: int64

In [11]:
df['title'].sample(20,random_state=42)

213    🔴 GTA 5 LIVE – DON’T BLINK! SECRET MOD ACTIVAT...
331    1,50,000 UC DARK MUMMY SET OPENING | JONATHAN ...
501    Piya O Re Piya | Riteish Deshmukh | Genelia D'...
309    🔴GTA V LIVE 🔥#shortsfeed #shortslive #gta #sho...
88     SHINCHAN AND FRANKLIN TRIED CRAZY ZIGZAG CURVY...
535    Thassadiya - Film Version | Maa Inti Bangaaram...
280    জ্যাকদের শহরে ঢুকে পড়লো এক ভয়ানক ডাইনি | শিন...
107    Attention Seeker - Babbu Maan | Latest Punabi ...
59                    HANTU HAMOOD HABIBI HORROR GAME 😨👹
506    RNX WARZONE INVITATIONAL  | Qualifiers Day 2 #...
359       Minecraft But You Can Travel 1,000,000 Blocks!
445    Expiry Date Trailer 4k l #nrfm #trailer #nrfmb...
70     Dada: The Sourav Ganguly Story | Official Trai...
96     HUGGY WUGGY IS BACK | POPPY PLAYTIME CHAPTER 5...
857    TOXIC - Notion Trailer | Yash | Nayanthara | R...
749    TOXIC First Trailer (Telugu) | Rocking Star Ya...
863    Woh Tassavur Ka Aalam - Lyrical | Woh Pyaar Py...
931    TERA CHEHRA(Title Track): Adnan Sami | Rani Mu...
76     🔥Chhodh Ke Na Jaa Ooh Piya 👍(Lyrical Video)1Al...
767    KHADAR (Official Video) Gaibu Gani | Latest Ja...
Name: title, dtype: object

In [12]:
df['channel_name'].sample(20,random_state=42)

213                              MR RAJA PLAYZONE
331                               JONATHAN GAMING
501                                 Gaane Jukebox
309                                  ADITYAISLIVE
88                                   Yippi Gaming
535                            Think Music Telugu
280                                  Lunatic Bong
107                                    Babbu Maan
59                                  MOSTIR DUNIYA
506                                   ROCKY & RDX
359                                    ProBoiz 95
445                                 NRFM BROTHERS
70                                   Uncut Cinema
96                                  Techno Gamerz
857                            Pan India Trailers
749    H-series Studio  4.1M views . 9hrs ago....
863                               hindi old songs
931                              Pop Chartbusters
76                                   YT GAMING FF
767                                    Gaibu Gani
Name: channel_name, dtype: object

In [13]:
df['keywords'].sample(20,random_state=42)

213    gta, live, don, blink, secret, mod, activated,...
331    000, dark, mummy, set, opening, jonathan, back...
501    piya, riteish, deshmukh, genelia, souza, atif,...
309      gta, live, shortsfeed, shortslive, shorts, gta5
88     shinchan, franklin, tried, crazy, zigzag, curv...
535    thassadiya, film, version, maa, inti, bangaara...
280             indian, theft, auto, simulator, gameplay
107    attention, seeker, babbu, maan, latest, punabi...
59                   hantu, hamood, habibi, horror, game
506    rnx, warzone, invitational, qualifiers, day, f...
359             minecraft, you, can, travel, 000, blocks
445                     expiry, date, nrfm, nrfmbrothers
70     dada, sourav, ganguly, story, rajkumar, rao, t...
96          huggy, wuggy, back, poppy, playtime, chapter
857    toxic, notion, yash, nayanthara, rukmini, kiar...
749    toxic, first, telugu, rocking, star, yash, nay...
863    woh, tassavur, aalam, lyrical, pyaar, udit, al...
931    tera, chehra, title, track, adnan, sami, rani,...
76     chhodh, jaa, ooh, piya, lyrical, 1alka, yagnik...
767    khadar, gaibu, gani, latest, janapada, kannada...
Name: keywords, dtype: object

In [14]:
(df['views']<0).sum() # invalid values

np.int64(0)

In [15]:
(df['likes']<0).sum()

np.int64(0)

In [16]:
(df['comments']<0).sum()

np.int64(0)

In [17]:
(df == "").sum() #empty string

video_id           0
title              0
channel_name       0
published_at       0
views              0
likes              0
comments           0
tags               0
keywords           0
video_url          0
collection_date    0
channel            0
dtype: int64

In [18]:
(df['title'] == "").sum()

np.int64(0)

In [19]:
(df['channel_name'] == "").sum()

np.int64(0)

In [20]:
df.describe()

              views          likes       comments  channel
count  9.890000e+02     989.000000     989.000000      0.0
mean   6.772642e+05   16959.965622    1150.371082      NaN
std    1.827948e+06   52570.988262    5316.214031      NaN
min    6.021000e+03       0.000000       0.000000      NaN
25%    8.363000e+04     891.000000       9.000000      NaN
50%    2.105860e+05    2989.000000      71.000000      NaN
75%    5.081160e+05   11004.000000     551.000000      NaN
max    2.529529e+07  640344.000000  127006.000000      NaN

In [21]:
# url validation

df['video_url'].str.startswith("https://").all()

np.True_

In [22]:
# Date validation
df['published_at'].head()

0    2026-07-09T07:16:37Z
1    2026-07-09T07:16:08Z
2    2026-07-09T07:03:02Z
3    2026-07-09T07:01:27Z
4    2026-07-09T06:00:06Z
Name: published_at, dtype: object

# Data Cleaning

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 989 entries, 0 to 988
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   video_id         989 non-null    object
 1   title            989 non-null    object
 2   channel_name     989 non-null    object
 3   published_at     989 non-null    object
 4   views            989 non-null    int64
 5   likes            989 non-null    int64
 6   comments         989 non-null    int64
 7   tags             989 non-null    object
 8   keywords         984 non-null    object
 9   video_url        989 non-null    object
 10  collection_date  989 non-null    object
 11  channel          0 non-null      float64
dtypes: float64(1), int64(3), object(8)
memory usage: 92.8+ KB

In [24]:
df.drop(columns=['channel'],inplace=True)

In [25]:
df.columns

Index(['video_id', 'title', 'channel_name', 'published_at', 'views', 'likes',
       'comments', 'tags', 'keywords', 'video_url', 'collection_date'],
      dtype='object')

In [26]:
df['keywords'] = df['keywords'].fillna("Not Avilable")

In [27]:
df['keywords'].isnull().sum()

np.int64(0)

In [28]:
df['published_at'] = pd.to_datetime(df['published_at'])

In [29]:
df['published_at'].dtypes

datetime64[ns, UTC]

In [30]:
df['collection_date'] = pd.to_datetime(df['collection_date'],dayfirst=True)

In [31]:
df['collection_date'].dtypes

dtype('<M8[ns]')

In [32]:
df.dtypes

video_id                        object
title                           object
channel_name                    object
published_at       datetime64[ns, UTC]
views                            int64
likes                            int64
comments                         int64
tags                            object
keywords                        object
video_url                       object
collection_date         datetime64[ns]
dtype: object

In [33]:
df.sample()

,video_id,title,channel_name,published_at,views,likes,comments,tags,keywords,video_url,collection_date
53,iNUSkEC5IcY,Franklin Found Shinchan's Secret base Inside t...,Happy Gamer,2026-07-08 10:30:02+00:00,47911,466,43,"Franklin shinchan video, shinchan show video, ...","franklin, found, shinchan, secret, base, insid...",https://www.youtube.com/watch?v=iNUSkEC5IcY,2026-07-09

In [34]:
df.drop_duplicates(inplace=True)

In [35]:
df.duplicated().sum()

np.int64(0)

In [36]:
# clean text col 
text_col = ['title','channel_name','tags','keywords']

for col in text_col: 
    df[col] = df[col].str.strip()

In [37]:
# final data validation 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 989 entries, 0 to 988
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   video_id         989 non-null    object
 1   title            989 non-null    object
 2   channel_name     989 non-null    object
 3   published_at     989 non-null    datetime64[ns, UTC]
 4   views            989 non-null    int64
 5   likes            989 non-null    int64
 6   comments         989 non-null    int64
 7   tags             989 non-null    object
 8   keywords         989 non-null    object
 9   video_url        989 non-null    object
 10  collection_date  989 non-null    datetime64[ns]
dtypes: datetime64[ns, UTC](1), datetime64[ns](1), int64(3), object(6)
memory usage: 85.1+ KB

In [38]:
df.isnull().sum()

video_id           0
title              0
channel_name       0
published_at       0
views              0
likes              0
comments           0
tags               0
keywords           0
video_url          0
collection_date    0
dtype: int64

In [39]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.to_csv("../data/cleaned/youtube_clean.csv",index=False)
print('save')

In [42]:
original_rows = df.shape[0]
clean_rows = df.shape[0]

print("=" * 50)
print("YOUTUBE TRENDS DATA CLEANING REPORT")
print("=" * 50)


print(f"Original Rows :     {original_rows}")
print(f"Cleaned Rows  :     {clean_rows}")
print(f"Rows Removed :     {original_rows - clean_rows}")
print(f"Columns :     {df.shape[1]}")
print(f"Duplicate Rows :     {df.duplicated().sum()}")


missing = df.isnull().sum()

print("\nMissing Values")
print(missing)

==================================================
YOUTUBE TRENDS DATA CLEANING REPORT
==================================================
Original Rows :     989
Cleaned Rows  :     989
Rows Removed :     0
Columns :     11
Duplicate Rows :     0

Missing Values
video_id           0
title              0
channel_name       0
published_at       0
views              0
likes              0
comments           0
tags               0
keywords           0
video_url          0
collection_date    0
dtype: int64

In [43]:
from sqlalchemy import create_engine 

engine = create_engine( "postgresql+psycopg2://postgres:MALI8261@localhost:5432/india_trend_radar")

In [44]:
df.to_sql('youtube_trends',engine,if_exists='replace',index=False)
print("Data loaded successfully into PostgreSQL")

Data loaded successfully into PostgreSQL

In [41]:
## Data Cleaning Summary

# - Removed the `channel` column due to 100% missing values.
# - Replaced missing values in the `keywords` column with "Not Available".
# - Converted `published_at` and `collection_date` to datetime format.
# - Ensured numeric columns had appropriate data types.
# - Removed duplicate records (if any).
# - Trimmed leading and trailing spaces from text columns.
# - Saved the cleaned dataset for database loading.

In [45]:
df.head()

,video_id,title,channel_name,published_at,views,likes,comments,tags,keywords,video_url,collection_date
0,KfT7AtKWS-A,GTA 5 LIVE | Train vs 100 Luxury Cars 😱🔥 कौन ब...,Sunil Gaming,2026-07-09 07:16:37+00:00,212532,1979,0,"gta 5 live, gta v train vs cars, gta 5 experim...","gta, live, train, 100, luxury, cars",https://www.youtube.com/watch?v=KfT7AtKWS-A,2026-07-09
1,Bp5Cq7PxQio,GTA 5 MOD LIVE | FULL TIMEPASS #gta #gtav #gaming,Gaming Anup Live,2026-07-09 07:16:08+00:00,432956,7631,0,"Gaming Anup, Gaming Anup shorts, Free fire, Ga...","gta, mod, live, timepass, gtav, gaming",https://www.youtube.com/watch?v=Bp5Cq7PxQio,2026-07-09
2,rwoT_ky5bnk,"09 जुलाई का मौसम| today weather update, heat w...",UMB NEWS,2026-07-09 07:03:02+00:00,118690,553,0,"mausam, mausam ki jankari, skymet weather fore...","today, weather, update, heat, wave, mausam, ja...",https://www.youtube.com/watch?v=rwoT_ky5bnk,2026-07-09
3,CWsACCb4vFg,GRANNY -1 LIVE 😉😱| GRANNY GAMEPLAY | #shorts #...,BOBIislive,2026-07-09 07:01:27+00:00,348481,8304,0,No Tags,"granny, live, gameplay, shorts, shortsfeed, sh...",https://www.youtube.com/watch?v=CWsACCb4vFg,2026-07-09
4,Zy8KDEJU3iY,"Bhai Tera Star Hai| Official Trailer| Raghav, ...",Eastwood Pictures Official,2026-07-09 06:00:06+00:00,16725,4990,198,#bhaiterastarhai,"bhai, tera, star, hai, raghav, niharika, vikal...",https://www.youtube.com/watch?v=Zy8KDEJU3iY,2026-07-09